services:
  frontend:
    build: .
    container_name: vue-frontend
    volumes:
    - .:/app:cached
    - /app/node_modules
    - /app/.nuxt
    ports:
      - "3001:3001"
    networks:
      - symfony

networks:
  symfony:
    external: true
