services:
  frontend:
    build: .
    container_name: vue-frontend
    volumes:
      - .:/app:cached
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - symfony

networks:
  symfony:
    external: true
