services:
  frontend:
    build: .
    container_name: vue-frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    networks:
      - symfony

networks:
  symfony:
    external: true
